# Generated by Django 5.0.7 on 2024-08-13 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 620014))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 620014))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 620014))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 620014))),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 621012))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 23, 1, 621012))),
                ('category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='web_app.category')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web_app.users')),
            ],
        ),
    ]
