# Generated by Django 5.0.7 on 2024-08-13 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
        migrations.AlterField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
        migrations.AlterField(
            model_name='records',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 2, 43, 51, 792363)),
        ),
    ]
