# Generated by Django 5.0.7 on 2024-08-14 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
        migrations.AlterField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
        migrations.AlterField(
            model_name='records',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 14, 13, 53, 20, 660430)),
        ),
    ]
